name: Build, Push to Docker Hub & Deploy to Render

on:
  push:
    branches:
      - main # Trigger on push to main
  pull_request:
    branches:
      - main # Trigger on PR to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Login to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t 9110112/car-rental-app:latest .

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push 9110112/car-rental-app:latest

      # Step 6: Trigger Render Deployment
      - name: Trigger Render Deployment
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d09mtpogjchc739an870?key=q0OKD9Qz5eA"
